import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import Layout from './components/layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'QR Code Scanner',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main>
                    <Layout>
                        {children}
                    </Layout>
                </main>
            </body>
        </html>
    )
}

